### ISSUE TITLE
raid0 error on EX100

### ISSUE THREAD

**Issue by tropo76** [hetzneronline/installimage#49]
hello, 

we can not use SWRAIDLEVEL 0 with EX100 installimage partition configuration.

PART /boot/efi esp 256M
PART swap swap 4G
PART /boot ext3 1024M
PART / ext4 all

It seems the EFI ESP does not accept raid0

this PART is not on AX installimage configuration
I have no issue on AX servers.

**Comment by asciiprod** [comment]
The EFI System Partition (ESP) is always treated special because it UEFI firmware cannot read RAID arrays. As such it is either created as plain FAT32 partitions or as a special RAID1 which does not look like a RAID to the UEFI firmware.
Also /boot will always be created as RAID1.
In summary the SWRAIDLEVEL applies to all partitions except the ESP and /boot.
